-- SQL UPDATE to set r2_folder for each drama
-- Run this AFTER running add_r2_folder_column.sql

UPDATE dramas SET r2_folder = '1955 Married the Mafia Boss by Contract (1198)' WHERE title = '1955: Married the Mafia Boss by Contract';
UPDATE dramas SET r2_folder = 'Adik lpar Memanjakanku（Dubbing） (894)' WHERE title = 'Adik lpar Memanjakanku（Dubbing）';
UPDATE dramas SET r2_folder = 'Aku Direkomendasikan, Kamu Bebas  (2825)' WHERE title = 'Aku Direkomendasikan, Kamu Bebas ';
UPDATE dramas SET r2_folder = 'Aku Ditakdirkan Milikmu (5190)' WHERE title = 'Aku Ditakdirkan Milikmu';
UPDATE dramas SET r2_folder = 'Anak Durhakaku (2672)' WHERE title = 'Anak Durhakaku';
UPDATE dramas SET r2_folder = 'Anak Imut Turun dari Langit (5136)' WHERE title = 'Anak Imut Turun dari Langit';
UPDATE dramas SET r2_folder = 'Ayah Pacarku, Suamiku (3108)' WHERE title = 'Ayah Pacarku, Suamiku';
UPDATE dramas SET r2_folder = 'Azab dari Dewi Pena (5119)' WHERE title = 'Azab dari Dewi Pena';
UPDATE dramas SET r2_folder = 'Cinta Di Ujung Senja (721)' WHERE title = 'Cinta Di Ujung Senja';
UPDATE dramas SET r2_folder = 'Cinta Di Ujung Senja（Dubbing） (978)' WHERE title = 'Cinta Di Ujung Senja（Dubbing）';
UPDATE dramas SET r2_folder = 'Cinta Diam Jadi Nyata (5194)' WHERE title = 'Cinta Diam Jadi Nyata';
UPDATE dramas SET r2_folder = 'Cinta Tanpa Keraguan (5122)' WHERE title = 'Cinta Tanpa Keraguan';
UPDATE dramas SET r2_folder = 'Cintaku Hadir Di Kehidupan Selanjutnya (487)' WHERE title = 'Cintaku Hadir Di Kehidupan Selanjutnya';
UPDATE dramas SET r2_folder = 'Godaan Sengaja (5071)' WHERE title = 'Godaan Sengaja';
UPDATE dramas SET r2_folder = 'Godaan di Malam Hari (4009)' WHERE title = 'Godaan di Malam Hari';
UPDATE dramas SET r2_folder = 'Hari Tunangan Anakku, Kubatalkan (3495)' WHERE title = 'Hari Tunangan Anakku, Kubatalkan';
UPDATE dramas SET r2_folder = 'Istri Gemuk Dimanjakan (5137)' WHERE title = 'Istri Gemuk Dimanjakan';
UPDATE dramas SET r2_folder = 'Istri Kesayangan Mafia (495)' WHERE title = 'Istri Kesayangan Mafia';
UPDATE dramas SET r2_folder = 'Istri Kesayangan Mafia（Dubbing） (977)' WHERE title = 'Istri Kesayangan Mafia（Dubbing）';
UPDATE dramas SET r2_folder = 'Jangan Ganggu Nenek (5235)' WHERE title = 'Jangan Ganggu Nenek';
UPDATE dramas SET r2_folder = 'Kebenaran Tak Terkubur (5202)' WHERE title = 'Kebenaran Tak Terkubur';
UPDATE dramas SET r2_folder = 'Kejayaanku Setelah Berpisah (963)' WHERE title = 'Kejayaanku Setelah Berpisah';
UPDATE dramas SET r2_folder = 'Kok Nyonya Gitu Kejam_ (5089)' WHERE title = 'Kok Nyonya Gitu Kejam?';
UPDATE dramas SET r2_folder = 'Maaf, Anak Ini Bukan Milikmu (5159)' WHERE title = 'Maaf, Anak Ini Bukan Milikmu';
UPDATE dramas SET r2_folder = 'Makin Ditahan, Makin Penasaran (3985)' WHERE title = 'Makin Ditahan, Makin Penasaran';
UPDATE dramas SET r2_folder = 'Masa Bersinarku (4464)' WHERE title = 'Masa Bersinarku';
UPDATE dramas SET r2_folder = 'Menaklukkan Suami Nakal (4784)' WHERE title = 'Menaklukkan Suami Nakal';
UPDATE dramas SET r2_folder = 'Menikah lagi dengan Ketua Direksi(Dubbing) (533)' WHERE title = 'Menikah lagi dengan Ketua Direksi(Dubbing)';
UPDATE dramas SET r2_folder = 'Naga Emas Lahir, Takdir Berbalik (5135)' WHERE title = 'Naga Emas Lahir, Takdir Berbalik';
UPDATE dramas SET r2_folder = 'Nenek Muda_ Kebangkitan Keluarga 2 (2186)' WHERE title = 'Nenek Muda: Kebangkitan Keluarga 2';
UPDATE dramas SET r2_folder = 'Nenek Muda_ Kebangkitan Keluarga 3 (3674)' WHERE title = 'Nenek Muda: Kebangkitan Keluarga 3';
UPDATE dramas SET r2_folder = 'Nikah Kontrak Berujung Cinta (2537)' WHERE title = 'Nikah Kontrak Berujung Cinta';
UPDATE dramas SET r2_folder = 'Nyonya Muda Si Mulut Sial (4187)' WHERE title = 'Nyonya Muda Si Mulut Sial';
UPDATE dramas SET r2_folder = 'Nyonya Muda Tak Terkalahkan 2 (4158)' WHERE title = 'Nyonya Muda Tak Terkalahkan 2';
UPDATE dramas SET r2_folder = 'Nyonya Muda yang Tidak Terkalahkan (2518)' WHERE title = 'Nyonya Muda yang Tidak Terkalahkan';
UPDATE dramas SET r2_folder = 'Nyonya Muda yang Tidak TerkalahkanDubbing (3764)' WHERE title = 'Nyonya Muda yang Tidak Terkalahkan(Dubbing)';
UPDATE dramas SET r2_folder = 'Pacarku Ternyata Dewi Kampus (5220)' WHERE title = 'Pacarku Ternyata Dewi Kampus';
UPDATE dramas SET r2_folder = 'Pangeran Merah Muda (5031)' WHERE title = 'Pangeran Merah Muda';
UPDATE dramas SET r2_folder = 'Pelukan landak (3832)' WHERE title = 'Pelukan landak';
UPDATE dramas SET r2_folder = 'Peramal Wanita (5247)' WHERE title = 'Peramal Wanita';
UPDATE dramas SET r2_folder = 'Romansa Om (5099)' WHERE title = 'Romansa Om';
UPDATE dramas SET r2_folder = 'Romansa di Rumah Mewah (4511)' WHERE title = 'Romansa di Rumah Mewah';
UPDATE dramas SET r2_folder = 'Salah Goda (4839)' WHERE title = 'Salah Goda';
UPDATE dramas SET r2_folder = 'Sang Putri Dilindungi Ibu (5043)' WHERE title = 'Sang Putri Dilindungi Ibu';
UPDATE dramas SET r2_folder = 'Sayang, Aku Benaran Amnesia (3164)' WHERE title = 'Sayang, Aku Benaran Amnesia';
UPDATE dramas SET r2_folder = 'Sekata dalam Diam (1859)' WHERE title = 'Sekata dalam Diam';
UPDATE dramas SET r2_folder = 'Suami Miskin Jadi Bos (5226)' WHERE title = 'Suami Miskin Jadi Bos';
UPDATE dramas SET r2_folder = 'Tak Bisa Melepasmu (2858)' WHERE title = 'Tak Bisa Melepasmu';
UPDATE dramas SET r2_folder = 'Takdir Cinta dengan Kaisar(Dubbing) (1445)' WHERE title = 'Takdir Cinta dengan Kaisar(Dubbing)';